#!/usr/bin/env bash
# Auto-generated by bayes-monitor.sh — refreshing status display

# ── Check if a lock file represents a live process ──
# Returns 0 (true) if alive, 1 (false) if dead. Cleans up stale locks.
lock_alive() {
    local lock="$1"
    [[ -f "$lock" ]] || return 1
    local pid
    pid=$(cat "$lock" 2>/dev/null) || return 1
    [[ -n "$pid" ]] || return 1
    if kill -0 "$pid" 2>/dev/null; then
        return 0
    else
        # Stale lock — process is dead, clean up
        rm -f "$lock" 2>/dev/null
        return 1
    fi
}

# ── Per-core CPU usage from /proc/stat ──
# Takes two snapshots 1s apart and computes busy% per core.
cpu_bars() {
    local ncpu
    ncpu=$(nproc)

    # Snapshot 1
    declare -A idle1 total1
    while IFS= read -r line; do
        local cpu rest
        cpu=$(echo "$line" | awk '{print $1}')
        [[ "$cpu" == cpu[0-9]* ]] || continue
        local fields
        read -ra fields <<< "$line"
        local sum=0
        for v in "${fields[@]:1}"; do sum=$((sum + v)); done
        local idle_val="${fields[4]}"
        total1[$cpu]=$sum
        idle1[$cpu]=$idle_val
    done < /proc/stat

    sleep 1

    # Snapshot 2
    declare -A idle2 total2
    while IFS= read -r line; do
        local cpu rest
        cpu=$(echo "$line" | awk '{print $1}')
        [[ "$cpu" == cpu[0-9]* ]] || continue
        local fields
        read -ra fields <<< "$line"
        local sum=0
        for v in "${fields[@]:1}"; do sum=$((sum + v)); done
        local idle_val="${fields[4]}"
        total2[$cpu]=$sum
        idle2[$cpu]=$idle_val
    done < /proc/stat

    # Compute and display
    local i=0
    local line1="  "
    local line2="  "
    for ((i=0; i<ncpu; i++)); do
        local cpu="cpu${i}"
        local dt=$(( ${total2[$cpu]} - ${total1[$cpu]} ))
        local di=$(( ${idle2[$cpu]} - ${idle1[$cpu]} ))
        local pct=0
        if [[ $dt -gt 0 ]]; then
            pct=$(( (dt - di) * 100 / dt ))
        fi

        # 4-char bar: ████, ███·, ██··, █···, ····
        local filled=$(( pct * 4 / 100 ))
        [[ $pct -gt 0 && $filled -eq 0 ]] && filled=1
        local bar=""
        local j
        for ((j=0; j<filled; j++)); do bar+="█"; done
        for ((j=filled; j<4; j++)); do bar+="·"; done

        # Colour: green < 50%, yellow 50-80%, red > 80%
        local colour
        if [[ $pct -lt 50 ]]; then colour="\033[32m";    # green
        elif [[ $pct -lt 80 ]]; then colour="\033[33m";   # yellow
        else colour="\033[31m"; fi                         # red

        local label
        printf -v label "%2d" "$i"
        line1+="${label}  "
        line2+="${colour}${bar}\033[0m"
        # Space between cores, extra space every 4
        if (( (i + 1) % 4 == 0 )); then
            line1+="  "
            line2+="  "
        fi
    done
    echo -e "  CPU"
    echo -e "$line1"
    echo -e "$line2"
}

# ── Kill all harness processes ──
kill_all() {
    local killed=0
    for lock in /tmp/bayes-harness-*.lock; do
        [[ -f "$lock" ]] || continue
        local pid
        pid=$(cat "$lock" 2>/dev/null)
        if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then
            kill -- -"$pid" 2>/dev/null || kill "$pid" 2>/dev/null || true
            killed=$((killed + 1))
        fi
        # Clean up lock file regardless (process is dead or just killed)
        rm -f "$lock" 2>/dev/null
    done
    # Also kill param_recovery background processes
    if [[ -f /tmp/bayes_recovery_pids ]]; then
        while read -r pid; do
            kill "$pid" 2>/dev/null || true
            killed=$((killed + 1))
        done < /tmp/bayes_recovery_pids
        rm -f /tmp/bayes_recovery_pids
    fi
    echo "  Killed ${killed} processes."
}

# ── Main loop ──
# Strategy: collect ALL data first (CPU poll is the slow part — 1s),
# then build the full frame into a buffer, then clear+dump in one go.
# This avoids the visible redraw flicker.
while true; do

    # ── 1. Poll CPU (1s blocking) ──
    cpu_output=$(cpu_bars)

    # ── 2. Parse job status from log files (fast) ──
    job_lines=""
    running_count=0
    for f in /tmp/bayes_harness-*.log; do
        [[ -f "$f" ]] || continue
        name=$(basename "$f" .log)
        name="${name#bayes_harness-}"
        lock="/tmp/bayes-harness-${name}.lock"

        if lock_alive "$lock"; then
            marker="*"
            running_count=$((running_count + 1))
        else
            marker=" "
            # Show finished jobs if log is non-empty (they were recent enough
            # to have log content). Only skip truly stale empty files.
            if [[ ! -s "$f" ]]; then
                continue
            fi
        fi

        last_line=$(grep -E '^\s+\[' "$f" 2>/dev/null | tail -1)
        if [[ -n "$last_line" ]]; then
            pct=$(echo "$last_line" | grep -oP '\[\s*\K\d+(?=%)' || echo "?")
            elapsed=$(echo "$last_line" | grep -oP '\d+\.\ds' || echo "?")
            stage=$(echo "$last_line" | grep -oP '(compiling|sampling|summarising|startup)' || echo "?")
            detail=$(echo "$last_line" | sed 's/.*: //')
        else
            pct="?"
            elapsed="?"
            stage="waiting"
            detail=""
        fi

        if grep -q "^PASS$\|^FAIL$\|=== FINISHED" "$f" 2>/dev/null; then
            result=$(grep -oP '(PASS|FAIL)' "$f" | tail -1)
            stage="done"
            detail="$result"
        fi

        job_lines+=$(printf "  %-28s %s%-12s %7s  %s\n" "$name" "$marker" "[${stage} ${pct}%]" "$elapsed" "$detail")
        job_lines+=$'\n'
    done

    # ── 3. Build frame and dump at once ──
    frame=""
    frame+="═══════════════════════════════════════════════════════════════════"$'\n'
    frame+="  BAYES MONITOR  $(date '+%H:%M:%S')"$'\n'
    frame+="═══════════════════════════════════════════════════════════════════"$'\n'
    frame+="${cpu_output}"$'\n'
    frame+=""$'\n'
    frame+=$(printf "  %-28s %-14s %7s  %s\n" "GRAPH" "STAGE" "ELAPSED" "DETAIL")$'\n'
    frame+=$(printf "  %-28s %-14s %7s  %s\n" "─────" "─────" "───────" "──────")$'\n'
    frame+="${job_lines}"
    frame+="  * = running    ${running_count} active"$'\n'
    frame+="  [k] kill all  [r] reload  [q] quit"$'\n'

    clear
    echo -e "$frame"

    # ── 4. Wait for input or timeout ──
    read -t 4 -n 1 key 2>/dev/null || key=""
    case "$key" in
        k|K)
            kill_all
            sleep 2
            ;;
        r|R)
            # Immediate re-loop (skip the read timeout)
            continue
            ;;
        q|Q)
            tmux kill-session -t bayes-monitor 2>/dev/null || exit 0
            exit 0
            ;;
    esac
done
