#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Bayes job monitor — shows all active harness runs on this machine.
#
# Opens a tmux session with:
#   - Top pane: per-core CPU bars + job status summary + kill command
#   - Bottom panes: tailed harness logs, one per active run (up to 4)
#
# Tail panes are managed DYNAMICALLY — they appear when graphs start
# running and disappear when they finish, without restarting the monitor.
#
# Discovers runs from /tmp/bayes_harness-*.log + lock files.
# Works for any harness invocation — manual, param recovery, pytest, etc.
#
# Usage:
#   scripts/bayes-monitor.sh              # auto-discover active runs
#   scripts/bayes-monitor.sh --all        # show finished runs in status table
#   scripts/bayes-monitor.sh synth-simple-abc synth-mirror-4step   # specific graphs only
#
# In the monitor:
#   ^b k    Kill all running harness processes
#   ^b e    Clear finished logs
#   ^b g    Quit monitor
#   ^b [    Scroll (q to exit scroll)
#   ^b ↑↓  Switch pane
# ---------------------------------------------------------------------------

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SESSION="bayes-monitor"
STATUS_SCRIPT="${REPO_ROOT}/scripts/_bayes-status.sh"

# ---------------------------------------------------------------------------
# Parse arguments
# ---------------------------------------------------------------------------
SHOW_ALL=0
SELECTED=()

while [[ $# -gt 0 ]]; do
    case "$1" in
        --all) SHOW_ALL=1; shift ;;
        -*)    echo "Unknown option: $1"; exit 1 ;;
        *)     SELECTED+=("$1"); shift ;;
    esac
done

# Clear display-only hidden list from previous session
rm -f /tmp/_bayes_monitor_hidden

# Write filter file: if specific graphs requested, only tail those
FILTER_FILE="/tmp/_bayes_monitor_filter"
if [[ ${#SELECTED[@]} -gt 0 ]]; then
    printf "%s\n" "${SELECTED[@]}" > "$FILTER_FILE"
    echo "Filtering to ${#SELECTED[@]} graphs:"
    for g in "${SELECTED[@]}"; do echo "  - $g"; done
    echo ""
else
    rm -f "$FILTER_FILE"
    echo "Dynamic mode — tail panes appear/disappear as graphs run."
    echo ""
fi

# ---------------------------------------------------------------------------
# Create the status summary script (top pane runs this in a loop)
# ---------------------------------------------------------------------------
cat > "$STATUS_SCRIPT" << 'STATUSEOF'
#!/usr/bin/env bash
# Auto-generated by bayes-monitor.sh — refreshing status display
# with dynamic tail pane management on window 0.

SHOW_ALL="${BAYES_MONITOR_SHOW_ALL:-0}"

# ── Check if a log file name is a timestamped archive copy ──
# Archive pattern: *-YYYYMMDD-HHMMSS (before .log extension)
is_archive() {
    [[ "$1" =~ -[0-9]{8}-[0-9]{6}$ ]]
}

# ── Check if a lock file represents a live process ──
lock_alive() {
    local lock="$1"
    [[ -f "$lock" ]] || return 1
    local pid
    pid=$(cat "$lock" 2>/dev/null) || return 1
    [[ -n "$pid" ]] || return 1
    if kill -0 "$pid" 2>/dev/null; then
        return 0
    else
        rm -f "$lock" 2>/dev/null
        return 1
    fi
}

# ── Get graphs eligible for tail panes (running first, then finished) ──
# Returns one name per line: running graphs first (sorted), then finished
# graphs (sorted).  Skips archive log files.  Caller picks up to 4.
# If a filter file exists, only returns graphs matching the filter.
get_tail_graphs() {
    local filter_file="/tmp/_bayes_monitor_filter"
    local running=() finished=()
    for f in /tmp/bayes_harness-*.log; do
        [[ -f "$f" ]] || continue
        local name
        name=$(basename "$f" .log)
        name="${name#bayes_harness-}"
        is_archive "$name" && continue
        [[ ! -s "$f" ]] && continue          # skip empty logs
        # If filter is set, check against it (match full name or stripped name)
        if [[ -f "$filter_file" ]]; then
            local short="${name#graph-}"
            if ! grep -qxF "$name" "$filter_file" 2>/dev/null &&
               ! grep -qxF "$short" "$filter_file" 2>/dev/null; then
                continue
            fi
        fi
        local lock="/tmp/bayes-harness-${name}.lock"
        # Skip graphs hidden by ^b e (display-only, logs untouched)
        local hidden_file="/tmp/_bayes_monitor_hidden"
        if [[ -f "$hidden_file" ]] && grep -qxF "$name" "$hidden_file" 2>/dev/null; then
            # Un-hide if it started running again
            if ! lock_alive "$lock"; then
                continue
            fi
        fi
        if lock_alive "$lock"; then
            running+=("$name")
        else
            finished+=("$name")
        fi
    done
    # Running first (sorted), then finished (sorted by most-recently-modified first)
    printf '%s\n' "${running[@]}" 2>/dev/null | sort -u
    # Sort finished by mtime descending so the most recent finish is shown first
    for fn in "${finished[@]}"; do
        echo "$fn"
    done 2>/dev/null | while IFS= read -r fn; do
        local ts
        ts=$(stat -c '%Y' "/tmp/bayes_harness-${fn}.log" 2>/dev/null) || ts=0
        echo "$ts $fn"
    done | sort -rn | awk '{print $2}'
}

# ── Write a tail script for a graph ──
write_tail_script() {
    local graph="$1" script_path="$2"
    local short="${graph#synth-}"
    short="${short#graph-}"
    local log_file="/tmp/bayes_harness-${graph}.log"
    cat > "$script_path" << INNER
#!/usr/bin/env bash
echo '─── ${short} ───'
while [[ ! -s "${log_file}" ]]; do sleep 0.5; done
exec tail -n 100 -f "${log_file}"
INNER
    chmod +x "$script_path"
}

# ── Rebuild tail panes on window 0 ──
# Kills all panes except pane 0 (status), then creates up to 4 tail panes
# using the same 2×2 grid layout.
rebuild_tails() {
    # Read running graphs into array
    local graphs=()
    while IFS= read -r g; do
        [[ -n "$g" ]] && graphs+=("$g")
    done <<< "$1"
    local n=${#graphs[@]}

    # Kill all panes except 0 (reverse order avoids index shifts)
    local pane_count
    pane_count=$(tmux list-panes -t "bayes-monitor:0" 2>/dev/null | wc -l) || return
    for ((p=pane_count-1; p>=1; p--)); do
        tmux kill-pane -t "bayes-monitor:0.$p" 2>/dev/null || true
    done

    [[ $n -eq 0 ]] && return
    [[ $n -gt 4 ]] && n=4

    # Layout:
    #   ┌──────────────────────────────────────┐
    #   │  status (pane 0)                     │  ~30%
    #   ├──────────────┬───────────────────────┤
    #   │  tail 1      │  tail 3               │  ~35%
    #   ├──────────────┼───────────────────────┤
    #   │  tail 2      │  tail 4               │  ~35%
    #   └──────────────┴───────────────────────┘

    # Step 1: split status from tail area (70% to bottom)
    local s0="/tmp/_bayes_tail_${graphs[0]}.sh"
    write_tail_script "${graphs[0]}" "$s0"
    tmux split-window -t "bayes-monitor:0.0" -v -l 70% "$s0" 2>/dev/null || true
    # Now: pane0=status, pane1=tail1

    if [[ $n -ge 2 ]]; then
        local s1="/tmp/_bayes_tail_${graphs[1]}.sh"
        write_tail_script "${graphs[1]}" "$s1"
        tmux split-window -t "bayes-monitor:0.1" -v -l 50% "$s1" 2>/dev/null || true
        # Now: pane0=status, pane1=tail1(top), pane2=tail2(bottom)
    fi

    if [[ $n -ge 3 ]]; then
        local s2="/tmp/_bayes_tail_${graphs[2]}.sh"
        write_tail_script "${graphs[2]}" "$s2"
        tmux split-window -t "bayes-monitor:0.1" -h -l 50% "$s2" 2>/dev/null || true
        # Now: pane0=status, pane1=tail1(TL), pane2=tail3(TR), pane3=tail2(bottom)
    fi

    if [[ $n -ge 4 ]]; then
        local s3="/tmp/_bayes_tail_${graphs[3]}.sh"
        write_tail_script "${graphs[3]}" "$s3"
        # pane3 is tail2(BL) — split it right
        tmux split-window -t "bayes-monitor:0.3" -h -l 50% "$s3" 2>/dev/null || true
    fi

    # Switch focus back to status pane
    tmux select-pane -t "bayes-monitor:0.0" 2>/dev/null || true
}

# ── Per-core CPU usage from /proc/stat ──
cpu_bars() {
    local ncpu
    ncpu=$(nproc)

    declare -A idle1 total1
    while IFS= read -r line; do
        local cpu rest
        cpu=$(echo "$line" | awk '{print $1}')
        [[ "$cpu" == cpu[0-9]* ]] || continue
        local fields
        read -ra fields <<< "$line"
        local sum=0
        for v in "${fields[@]:1}"; do sum=$((sum + v)); done
        local idle_val="${fields[4]}"
        total1[$cpu]=$sum
        idle1[$cpu]=$idle_val
    done < /proc/stat

    sleep 1

    declare -A idle2 total2
    while IFS= read -r line; do
        local cpu rest
        cpu=$(echo "$line" | awk '{print $1}')
        [[ "$cpu" == cpu[0-9]* ]] || continue
        local fields
        read -ra fields <<< "$line"
        local sum=0
        for v in "${fields[@]:1}"; do sum=$((sum + v)); done
        local idle_val="${fields[4]}"
        total2[$cpu]=$sum
        idle2[$cpu]=$idle_val
    done < /proc/stat

    local i=0
    local line1="  "
    local line2="  "
    for ((i=0; i<ncpu; i++)); do
        local cpu="cpu${i}"
        local dt=$(( ${total2[$cpu]} - ${total1[$cpu]} ))
        local di=$(( ${idle2[$cpu]} - ${idle1[$cpu]} ))
        local pct=0
        if [[ $dt -gt 0 ]]; then
            pct=$(( (dt - di) * 100 / dt ))
        fi

        local filled=$(( pct * 4 / 100 ))
        [[ $pct -gt 0 && $filled -eq 0 ]] && filled=1
        local bar=""
        local j
        for ((j=0; j<filled; j++)); do bar+="█"; done
        for ((j=filled; j<4; j++)); do bar+="·"; done

        local colour
        if [[ $pct -lt 50 ]]; then colour="\033[32m";
        elif [[ $pct -lt 80 ]]; then colour="\033[33m";
        else colour="\033[31m"; fi

        local label
        printf -v label "%2d" "$i"
        line1+="${label}  "
        line2+="${colour}${bar}\033[0m"
        if (( (i + 1) % 4 == 0 )); then
            line1+="  "
            line2+="  "
        fi
    done
    echo -e "  CPU"
    echo -e "$line1"
    echo -e "$line2"
}

# ── Clear handler (^b e sends USR1 to this process) ──
_do_clear=0
_handle_clear() { _do_clear=1; }
trap _handle_clear USR1
echo $$ > /tmp/_bayes_monitor_status_pid

# ── Main loop ──
_prev_tails=""
_start_epoch=$(date +%s)

while true; do

    # ── 0. Handle clear request (^b e) ──
    # Clears finished graphs from the MONITOR DISPLAY only.
    # Does NOT touch log files — they are primary diagnostic data.
    if [[ $_do_clear -eq 1 ]]; then
        _do_clear=0
        # Rebuild hidden list from scratch (avoids unbounded growth)
        rm -f /tmp/_bayes_monitor_hidden
        for f in /tmp/bayes_harness-*.log; do
            [[ -f "$f" ]] || continue
            _cname=$(basename "$f" .log)
            _cname="${_cname#bayes_harness-}"
            is_archive "$_cname" && continue
            _clock="/tmp/bayes-harness-${_cname}.lock"
            if ! lock_alive "$_clock"; then
                echo "$_cname" >> /tmp/_bayes_monitor_hidden
            fi
            # Clean up tail scripts for finished graphs only (not running)
            if ! lock_alive "$_clock"; then
                rm -f "/tmp/_bayes_tail_${_cname}.sh" 2>/dev/null
            fi
        done
        # Force tail rebuild on next cycle
        _prev_tails="__cleared__"
    fi

    # ── 1. Poll CPU (1s blocking) ──
    cpu_output=$(cpu_bars)

    # ── 2. Parse job status from log files (fast) ──
    declare -a job_names=() job_markers=() job_stages=() job_pcts=()
    declare -a job_elapsed=() job_details=()
    running_count=0
    for f in /tmp/bayes_harness-*.log; do
        [[ -f "$f" ]] || continue
        name=$(basename "$f" .log)
        name="${name#bayes_harness-}"
        # Skip archive copies
        is_archive "$name" && continue
        lock="/tmp/bayes-harness-${name}.lock"
        # Skip graphs hidden by ^b e — but un-hide if running again
        if [[ -f /tmp/_bayes_monitor_hidden ]] && grep -qxF "$name" /tmp/_bayes_monitor_hidden 2>/dev/null; then
            if ! lock_alive "$lock"; then
                continue
            fi
        fi

        if lock_alive "$lock"; then
            marker="*"
            running_count=$((running_count + 1))
        else
            marker=" "
            if [[ $SHOW_ALL -eq 0 ]]; then
                # Default mode: skip finished graphs from before monitor started
                mtime=$(stat -c '%Y' "$f" 2>/dev/null) || mtime=0
                if [[ $mtime -lt $_start_epoch ]]; then
                    continue
                fi
                # Still need PASS/FAIL marker to count as finished
                if ! grep -q "^PASS$\|^FAIL$\|=== FINISHED" "$f" 2>/dev/null; then
                    continue
                fi
            else
                [[ ! -s "$f" ]] && continue
            fi
        fi

        last_line=$(grep -E '^\s+\[' "$f" 2>/dev/null | tail -1)
        if [[ -n "$last_line" ]]; then
            pct=$(echo "$last_line" | grep -oP '\[\s*\K\d+(?=%)' || echo "?")
            elapsed=$(echo "$last_line" | grep -oP '\d+\.\ds' || echo "?")
            stage=$(echo "$last_line" | grep -oP '(compiling|sampling|summarising|startup|simulating|hashing|db_write|writing|verifying|done)' || echo "?")
            detail=$(echo "$last_line" | sed 's/[^:]*: //')
        else
            pct="?"
            elapsed="?"
            stage="waiting"
            detail=""
        fi

        if grep -q "^PASS$\|^FAIL$\|=== FINISHED" "$f" 2>/dev/null; then
            result=$(grep -oP '(PASS|FAIL)' "$f" | tail -1)
            stage="done"
            pct="100"
            detail="$result"
        fi

        job_names+=("$name")
        job_markers+=("$marker")
        job_stages+=("$stage")
        job_pcts+=("$pct")
        job_elapsed+=("$elapsed")
        job_details+=("$detail")
    done

    # ── 3. Compute dynamic column widths ──
    term_width=$(tput cols 2>/dev/null || echo 120)
    fixed=33
    max_name=$(( term_width - fixed - 20 ))
    [[ $max_name -lt 20 ]] && max_name=20

    longest_name=0
    for n in "${job_names[@]}"; do
        [[ ${#n} -gt $longest_name ]] && longest_name=${#n}
    done
    name_col=$longest_name
    [[ $name_col -gt $max_name ]] && name_col=$max_name
    [[ $name_col -lt 5 ]] && name_col=20

    trunc_name() {
        local n="$1" max="$2"
        if [[ ${#n} -le $max ]]; then
            echo "$n"
        else
            echo "${n:0:$((max-1))}…"
        fi
    }

    progress_bar() {
        local pct="$1" stage="$2" marker="$3"
        local bar_width=12
        if [[ "$pct" == "?" ]]; then
            printf "%s%-14s" "$marker" "[${stage}]"
            return
        fi
        local filled=$(( pct * bar_width / 100 ))
        [[ $pct -gt 0 && $filled -eq 0 ]] && filled=1
        local bar=""
        local j
        for ((j=0; j<filled; j++)); do bar+="█"; done
        for ((j=filled; j<bar_width; j++)); do bar+="░"; done
        local colour
        if [[ "$stage" == "done" ]]; then colour="\033[32m";
        elif [[ "$stage" == "compiling" || "$stage" == "simulating" || "$stage" == "hashing" ]]; then colour="\033[33m";
        else colour="\033[36m"; fi
        printf "%s${colour}%s\033[0m %3d%%" "$marker" "$bar" "$pct"
    }

    job_lines=""
    for ((idx=0; idx<${#job_names[@]}; idx++)); do
        dn=$(trunc_name "${job_names[$idx]}" "$name_col")
        bar_str=$(progress_bar "${job_pcts[$idx]}" "${job_stages[$idx]}" "${job_markers[$idx]}")
        stage_label="${job_stages[$idx]}"
        stage_label="$(echo "${stage_label:0:1}" | tr '[:lower:]' '[:upper:]')${stage_label:1}"
        job_lines+=$(printf "  %-${name_col}s %b  %-11s %7s  %s\n" \
            "$dn" "$bar_str" "$stage_label" "${job_elapsed[$idx]}" "${job_details[$idx]}")
        job_lines+=$'\n'
    done

    # ── 4. Build frame and dump at once ──
    sep=$(printf '═%.0s' $(seq 1 "$term_width"))
    n_tailed=$(tmux list-panes -t "bayes-monitor:0" 2>/dev/null | wc -l)
    n_tailed=$((n_tailed - 1))  # exclude status pane

    frame=""
    frame+="${sep}"$'\n'
    frame+="  BAYES MONITOR    $(date '+%H:%M:%S')    ${running_count} running  ${n_tailed} tailed"$'\n'
    frame+="${sep}"$'\n'
    frame+="${cpu_output}"$'\n'
    frame+=""$'\n'
    if [[ ${#job_names[@]} -gt 0 ]]; then
        frame+=$(printf "  %-${name_col}s %-18s %-11s %7s  %s\n" "GRAPH" "PROGRESS" "STAGE" "ELAPSED" "DETAIL")$'\n'
        frame+=$(printf "  %-${name_col}s %-18s %-11s %7s  %s\n" "─────" "────────" "─────" "───────" "──────")$'\n'
        frame+="${job_lines}"
    else
        frame+="  No harness logs found. Waiting for runs to start…"$'\n'
        frame+=""$'\n'
    fi
    frame+="  * = running"$'\n'
    frame+="  ^b k: kill all   ^b e: clear finished   ^b g: quit"$'\n'
    frame+="  ^b [: scroll (q to exit)   ^b ↑↓: switch pane"$'\n'

    clear
    echo -e "$frame"

    # ── 5. Dynamic tail pane management ──
    # Running graphs first, then finished (most recent first), cap at 4.
    # Only rebuild when the set actually changes.
    _current_tails=$(get_tail_graphs | head -4)
    if [[ "$_current_tails" != "$_prev_tails" ]]; then
        rebuild_tails "$_current_tails"
        _prev_tails="$_current_tails"
    fi

    # Use wait so USR1 signal can interrupt the sleep immediately
    sleep 4 &
    wait $! 2>/dev/null || true
done
STATUSEOF
chmod +x "$STATUS_SCRIPT"

# ---------------------------------------------------------------------------
# Build tmux session — single window, status pane only.
# Tail panes are created dynamically by the status script.
# ---------------------------------------------------------------------------
tmux kill-session -t "$SESSION" 2>/dev/null || true
tmux new-session -d -s "$SESSION" -n "monitor" \
    "BAYES_MONITOR_SHOW_ALL=${SHOW_ALL} bash $STATUS_SCRIPT"

# ---------------------------------------------------------------------------
# Keybindings
# ---------------------------------------------------------------------------
KILL_SCRIPT="${REPO_ROOT}/scripts/_bayes-kill.sh"
cat > "$KILL_SCRIPT" << 'KILLEOF'
#!/usr/bin/env bash
for lock in /tmp/bayes-harness-*.lock; do
    [[ -f "$lock" ]] || continue
    pid=$(cat "$lock" 2>/dev/null)
    if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then
        kill -- -"$pid" 2>/dev/null || kill "$pid" 2>/dev/null || true
    fi
    rm -f "$lock" 2>/dev/null
done
if [[ -f /tmp/bayes_recovery_pids ]]; then
    while read -r pid; do
        kill "$pid" 2>/dev/null || true
    done < /tmp/bayes_recovery_pids
    rm -f /tmp/bayes_recovery_pids
fi
KILLEOF
chmod +x "$KILL_SCRIPT"

tmux bind-key -N "Kill all bayes"   k run-shell "${KILL_SCRIPT}"
tmux bind-key -N "Clear finished"   e run-shell "kill -USR1 \$(cat /tmp/_bayes_monitor_status_pid 2>/dev/null) 2>/dev/null || true"
tmux bind-key -N "Quit monitor"     g kill-session -t "${SESSION}"

tmux set-option -t "$SESSION" -g history-limit 10000

echo "Monitor: tmux attach -t ${SESSION}"
echo "  Top:    status (CPU + jobs)"
echo "  Bottom: tail panes appear/disappear dynamically (up to 4)"
echo "  Keys:   ^b k=kill all  ^b e=clear finished  ^b g=quit"
echo "  ^b ↑↓: switch pane   ^b [: scroll"
echo ""

if [[ -t 0 ]]; then
    exec tmux attach -t "$SESSION"
fi
