#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Bayes job monitor — shows all active harness runs on this machine.
#
# Opens a tmux session with:
#   - Top pane: per-core CPU bars + job status summary + kill command
#   - Bottom panes: tailed harness logs, one per active run
#
# Discovers runs from /tmp/bayes_harness-*.log. Works for any harness
# invocation — manual, param recovery, pytest, etc.
#
# Usage:
#   scripts/bayes-monitor.sh              # auto-discover active runs (hides finished)
#   scripts/bayes-monitor.sh --all        # show all logs (including finished)
#   scripts/bayes-monitor.sh --clear      # delete old finished logs, then monitor
#   scripts/bayes-monitor.sh synth-simple-abc synth-mirror-4step   # specific graphs
#
# In the status pane:
#   k + Enter    Kill all running harness processes
#   q + Enter    Close the monitor
# ---------------------------------------------------------------------------

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SESSION="bayes-monitor"
STATUS_SCRIPT="${REPO_ROOT}/scripts/_bayes-status.sh"

# ---------------------------------------------------------------------------
# Parse arguments
# ---------------------------------------------------------------------------
SHOW_ALL=0
SELECTED=()

while [[ $# -gt 0 ]]; do
    case "$1" in
        --all) SHOW_ALL=1; shift ;;
        -*)    echo "Unknown option: $1"; exit 1 ;;
        *)     SELECTED+=("$1"); shift ;;
    esac
done

# ---------------------------------------------------------------------------
# Discover graphs — first from runner's graph list, then from log files
# ---------------------------------------------------------------------------
discover_graphs() {
    # Fallback: scan log files
    # Default (no --all): only show runs with an active lock (currently running).
    # Finished runs from previous sessions are hidden to reduce clutter.
    # --all: show everything.
    for f in /tmp/bayes_harness-*.log; do
        [[ -f "$f" ]] || continue
        local name
        name=$(basename "$f" .log)
        name="${name#bayes_harness-}"
        if [[ $SHOW_ALL -eq 1 ]]; then
            echo "$name"
        else
            local lock="/tmp/bayes-harness-${name}.lock"
            if [[ -f "$lock" ]]; then
                # Has a lock file — check if the process is actually alive
                local pid
                pid=$(cat "$lock" 2>/dev/null) || continue
                if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then
                    echo "$name"
                fi
            fi
        fi
    done
}

if [[ ${#SELECTED[@]} -eq 0 ]]; then
    while IFS= read -r g; do
        [[ -n "$g" ]] && SELECTED+=("$g")
    done < <(discover_graphs)
fi

if [[ ${#SELECTED[@]} -eq 0 ]]; then
    echo "No active bayes runs yet — starting monitor in standby."
    echo "  Tail panes will appear automatically when runs start."
    echo ""
else
    echo "Monitoring ${#SELECTED[@]} runs:"
    for g in "${SELECTED[@]}"; do echo "  - $g"; done
    echo ""
fi

# Record initial graph set so the status script can detect new arrivals
printf "%s\n" "${SELECTED[@]}" > /tmp/_bayes_monitor_initial_graphs

# ---------------------------------------------------------------------------
# Create the status summary script (top pane runs this in a loop)
# ---------------------------------------------------------------------------
cat > "$STATUS_SCRIPT" << 'STATUSEOF'
#!/usr/bin/env bash
# Auto-generated by bayes-monitor.sh — refreshing status display

# ── Check if a lock file represents a live process ──
# Returns 0 (true) if alive, 1 (false) if dead. Cleans up stale locks.
lock_alive() {
    local lock="$1"
    [[ -f "$lock" ]] || return 1
    local pid
    pid=$(cat "$lock" 2>/dev/null) || return 1
    [[ -n "$pid" ]] || return 1
    if kill -0 "$pid" 2>/dev/null; then
        return 0
    else
        # Stale lock — process is dead, clean up
        rm -f "$lock" 2>/dev/null
        return 1
    fi
}

# ── Per-core CPU usage from /proc/stat ──
# Takes two snapshots 1s apart and computes busy% per core.
cpu_bars() {
    local ncpu
    ncpu=$(nproc)

    # Snapshot 1
    declare -A idle1 total1
    while IFS= read -r line; do
        local cpu rest
        cpu=$(echo "$line" | awk '{print $1}')
        [[ "$cpu" == cpu[0-9]* ]] || continue
        local fields
        read -ra fields <<< "$line"
        local sum=0
        for v in "${fields[@]:1}"; do sum=$((sum + v)); done
        local idle_val="${fields[4]}"
        total1[$cpu]=$sum
        idle1[$cpu]=$idle_val
    done < /proc/stat

    sleep 1

    # Snapshot 2
    declare -A idle2 total2
    while IFS= read -r line; do
        local cpu rest
        cpu=$(echo "$line" | awk '{print $1}')
        [[ "$cpu" == cpu[0-9]* ]] || continue
        local fields
        read -ra fields <<< "$line"
        local sum=0
        for v in "${fields[@]:1}"; do sum=$((sum + v)); done
        local idle_val="${fields[4]}"
        total2[$cpu]=$sum
        idle2[$cpu]=$idle_val
    done < /proc/stat

    # Compute and display
    local i=0
    local line1="  "
    local line2="  "
    for ((i=0; i<ncpu; i++)); do
        local cpu="cpu${i}"
        local dt=$(( ${total2[$cpu]} - ${total1[$cpu]} ))
        local di=$(( ${idle2[$cpu]} - ${idle1[$cpu]} ))
        local pct=0
        if [[ $dt -gt 0 ]]; then
            pct=$(( (dt - di) * 100 / dt ))
        fi

        # 4-char bar: ████, ███·, ██··, █···, ····
        local filled=$(( pct * 4 / 100 ))
        [[ $pct -gt 0 && $filled -eq 0 ]] && filled=1
        local bar=""
        local j
        for ((j=0; j<filled; j++)); do bar+="█"; done
        for ((j=filled; j<4; j++)); do bar+="·"; done

        # Colour: green < 50%, yellow 50-80%, red > 80%
        local colour
        if [[ $pct -lt 50 ]]; then colour="\033[32m";    # green
        elif [[ $pct -lt 80 ]]; then colour="\033[33m";   # yellow
        else colour="\033[31m"; fi                         # red

        local label
        printf -v label "%2d" "$i"
        line1+="${label}  "
        line2+="${colour}${bar}\033[0m"
        # Space between cores, extra space every 4
        if (( (i + 1) % 4 == 0 )); then
            line1+="  "
            line2+="  "
        fi
    done
    echo -e "  CPU"
    echo -e "$line1"
    echo -e "$line2"
}

# ── Kill all harness processes ──
kill_all() {
    local killed=0
    for lock in /tmp/bayes-harness-*.lock; do
        [[ -f "$lock" ]] || continue
        local pid
        pid=$(cat "$lock" 2>/dev/null)
        if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then
            kill -- -"$pid" 2>/dev/null || kill "$pid" 2>/dev/null || true
            killed=$((killed + 1))
        fi
        # Clean up lock file regardless (process is dead or just killed)
        rm -f "$lock" 2>/dev/null
    done
    # Also kill param_recovery background processes
    if [[ -f /tmp/bayes_recovery_pids ]]; then
        while read -r pid; do
            kill "$pid" 2>/dev/null || true
            killed=$((killed + 1))
        done < /tmp/bayes_recovery_pids
        rm -f /tmp/bayes_recovery_pids
    fi
    echo "  Killed ${killed} processes."
}

# ── Clear handler (^b e sends USR1 to this process) ──
_do_clear=0
_handle_clear() { _do_clear=1; }
trap _handle_clear USR1
echo $$ > /tmp/_bayes_monitor_status_pid

# ── Main loop ──
# Strategy: collect ALL data first (CPU poll is the slow part — 1s),
# then build the full frame into a buffer, then clear+dump in one go.
# This avoids the visible redraw flicker.
while true; do

    # ── 0. Handle clear request (^b e) ──
    if [[ $_do_clear -eq 1 ]]; then
        _do_clear=0
        for f in /tmp/bayes_harness-*.log; do
            [[ -f "$f" ]] || continue
            _cname=$(basename "$f" .log)
            _cname="${_cname#bayes_harness-}"
            _clock="/tmp/bayes-harness-${_cname}.lock"
            if [[ -f "$_clock" ]]; then
                _cpid=$(cat "$_clock" 2>/dev/null)
                [[ -n "$_cpid" ]] && kill -0 "$_cpid" 2>/dev/null && continue
                rm -f "$_clock" 2>/dev/null
            fi
            rm -f "$f" 2>/dev/null
        done
        : > /tmp/_bayes_monitor_initial_graphs 2>/dev/null
    fi

    # ── 1. Poll CPU (1s blocking) ──
    cpu_output=$(cpu_bars)

    # ── 2. Parse job status from log files (fast) ──
    # Collect job data into arrays first, then format with dynamic widths
    declare -a job_names=() job_markers=() job_stages=() job_pcts=()
    declare -a job_elapsed=() job_details=()
    running_count=0
    for f in /tmp/bayes_harness-*.log; do
        [[ -f "$f" ]] || continue
        name=$(basename "$f" .log)
        name="${name#bayes_harness-}"
        lock="/tmp/bayes-harness-${name}.lock"

        if lock_alive "$lock"; then
            marker="*"
            running_count=$((running_count + 1))
        else
            marker=" "
            if [[ ! -s "$f" ]]; then
                continue
            fi
        fi

        last_line=$(grep -E '^\s+\[' "$f" 2>/dev/null | tail -1)
        if [[ -n "$last_line" ]]; then
            pct=$(echo "$last_line" | grep -oP '\[\s*\K\d+(?=%)' || echo "?")
            elapsed=$(echo "$last_line" | grep -oP '\d+\.\ds' || echo "?")
            stage=$(echo "$last_line" | grep -oP '(compiling|sampling|summarising|startup|simulating|hashing|db_write|writing|verifying|done)' || echo "?")
            detail=$(echo "$last_line" | sed 's/[^:]*: //')
        else
            pct="?"
            elapsed="?"
            stage="waiting"
            detail=""
        fi

        if grep -q "^PASS$\|^FAIL$\|=== FINISHED" "$f" 2>/dev/null; then
            result=$(grep -oP '(PASS|FAIL)' "$f" | tail -1)
            stage="done"
            pct="100"
            detail="$result"
        fi

        job_names+=("$name")
        job_markers+=("$marker")
        job_stages+=("$stage")
        job_pcts+=("$pct")
        job_elapsed+=("$elapsed")
        job_details+=("$detail")
    done

    # ── 3. Compute dynamic column widths ──
    term_width=$(tput cols 2>/dev/null || echo 120)
    # Fixed columns: marker(1) + stage_col(16) + elapsed(8) + spacing(8) = ~33
    fixed=33
    # Graph name gets remaining width, min 20, leave room for some detail
    max_name=$(( term_width - fixed - 20 ))  # 20 reserved for detail
    [[ $max_name -lt 20 ]] && max_name=20

    # Find longest name to see if we need truncation
    longest_name=0
    for n in "${job_names[@]}"; do
        [[ ${#n} -gt $longest_name ]] && longest_name=${#n}
    done
    # Use the shorter of longest name or max allowed
    name_col=$longest_name
    [[ $name_col -gt $max_name ]] && name_col=$max_name
    [[ $name_col -lt 5 ]] && name_col=20

    # Helper: truncate name with ellipsis if needed
    trunc_name() {
        local n="$1" max="$2"
        if [[ ${#n} -le $max ]]; then
            echo "$n"
        else
            echo "${n:0:$((max-1))}…"
        fi
    }

    # Helper: render a progress bar  ████████░░░░ 72%
    progress_bar() {
        local pct="$1" stage="$2" marker="$3"
        local bar_width=12
        if [[ "$pct" == "?" ]]; then
            # Unknown progress — show stage name only
            printf "%s%-14s" "$marker" "[${stage}]"
            return
        fi
        local filled=$(( pct * bar_width / 100 ))
        [[ $pct -gt 0 && $filled -eq 0 ]] && filled=1
        local bar=""
        local j
        for ((j=0; j<filled; j++)); do bar+="█"; done
        for ((j=filled; j<bar_width; j++)); do bar+="░"; done
        # Colour: green if done, yellow if in progress, red if compiling
        local colour
        if [[ "$stage" == "done" ]]; then colour="\033[32m";
        elif [[ "$stage" == "compiling" || "$stage" == "simulating" || "$stage" == "hashing" ]]; then colour="\033[33m";
        else colour="\033[36m"; fi
        printf "%s${colour}%s\033[0m %3d%%" "$marker" "$bar" "$pct"
    }

    # Build job lines with dynamic widths
    job_lines=""
    for ((idx=0; idx<${#job_names[@]}; idx++)); do
        dn=$(trunc_name "${job_names[$idx]}" "$name_col")
        bar_str=$(progress_bar "${job_pcts[$idx]}" "${job_stages[$idx]}" "${job_markers[$idx]}")
        stage_label="${job_stages[$idx]}"
        # Capitalise first letter of stage
        stage_label="$(echo "${stage_label:0:1}" | tr '[:lower:]' '[:upper:]')${stage_label:1}"
        job_lines+=$(printf "  %-${name_col}s %b  %-11s %7s  %s\n" \
            "$dn" "$bar_str" "$stage_label" "${job_elapsed[$idx]}" "${job_details[$idx]}")
        job_lines+=$'\n'
    done

    # ── 4. Build frame and dump at once ──
    sep=$(printf '═%.0s' $(seq 1 "$term_width"))
    frame=""
    frame+="${sep}"$'\n'
    frame+="  BAYES MONITOR    $(date '+%H:%M:%S')"$'\n'
    frame+="${sep}"$'\n'
    frame+="${cpu_output}"$'\n'
    frame+=""$'\n'
    frame+=$(printf "  %-${name_col}s %-18s %-11s %7s  %s\n" "GRAPH" "PROGRESS" "STAGE" "ELAPSED" "DETAIL")$'\n'
    frame+=$(printf "  %-${name_col}s %-18s %-11s %7s  %s\n" "─────" "────────" "─────" "───────" "──────")$'\n'
    frame+="${job_lines}"
    frame+="  * = running    ${running_count} active"$'\n'
    frame+="  ^b k: kill all   ^b e: clear finished   ^b j: reload   ^b g: quit"$'\n'
    frame+="  ^b [: scroll (q to exit)   ^b n/p: next/prev page"$'\n'

    clear
    echo -e "$frame"

    # ── 5. Absorb new graphs into the status display ──
    # If new harness log files or recovery graph entries appeared since
    # launch, add them to the initial set so they show up in the job
    # table above. We do NOT rebuild/exec — that kills the tmux session.
    # The tail panes stay fixed (showing the original set); the user can
    # Ctrl-b R to rebuild if they want new tail panes.
    _new_found=0
    for f in /tmp/bayes_harness-*.log; do
        [[ -f "$f" && -s "$f" ]] || continue
        _gname=$(basename "$f" .log)
        _gname="${_gname#bayes_harness-}"
        if ! grep -qxF "$_gname" /tmp/_bayes_monitor_initial_graphs 2>/dev/null; then
            echo "$_gname" >> /tmp/_bayes_monitor_initial_graphs
            _new_found=$((_new_found + 1))
        fi
    done
    if [[ -f /tmp/bayes_recovery_graphs ]]; then
        while IFS= read -r _rg; do
            [[ -n "$_rg" ]] || continue
            if ! grep -qxF "$_rg" /tmp/_bayes_monitor_initial_graphs 2>/dev/null; then
                echo "$_rg" >> /tmp/_bayes_monitor_initial_graphs
                _new_found=$((_new_found + 1))
            fi
        done < /tmp/bayes_recovery_graphs
    fi
    if [[ $_new_found -gt 0 ]]; then
        echo "  ${_new_found} new graph(s) detected — added to status display."
        echo "  Press Ctrl-b R to rebuild tail panes."
    fi

    # Use wait so USR1 signal can interrupt the sleep immediately
    sleep 4 &
    wait $! 2>/dev/null || true
done
STATUSEOF
chmod +x "$STATUS_SCRIPT"

# ---------------------------------------------------------------------------
# Build tmux session
#
# Layout per page (window):
#   ┌──────────────────────────────────────────┐
#   │  status (CPU + jobs)                     │  pane 0
#   ├─────────────────────┬────────────────────┤
#   │  tail graph 1       │  tail graph 2      │  pane 1, 2
#   ├─────────────────────┼────────────────────┤
#   │  tail graph 3       │  tail graph 4      │  pane 3, 4
#   └─────────────────────┴────────────────────┘
#
# Pages: window "page-1" has graphs 0-3, "page-2" has graphs 4-7, etc.
# Status pane duplicated per page so it's always visible.
# Navigate: Ctrl-b n / Ctrl-b p
# ---------------------------------------------------------------------------
PANES_PER_PAGE=4

tmux kill-session -t "$SESSION" 2>/dev/null || true

# Pre-create all log files
for graph in "${SELECTED[@]}"; do
    touch "/tmp/bayes_harness-${graph}.log"
done

n_graphs=${#SELECTED[@]}
n_pages=$(( (n_graphs + PANES_PER_PAGE - 1) / PANES_PER_PAGE ))

tail_cmd() {
    local graph="$1"
    local short="${graph#synth-}"
    short="${short#graph-}"
    # The harness may write the log under several name variants:
    #   bayes_harness-{graph}.log          (direct invocation)
    #   bayes_harness-graph-{graph}.log    (--fe-payload adds graph- prefix)
    # And SELECTED may contain a bare name while the log has graph- or
    # synth- prefixes.  Poll for whichever file gets content first.
    cat <<TAIL_SCRIPT
echo '─── ${short} ───'
while true; do
  for f in /tmp/bayes_harness-*${graph}*.log /tmp/bayes_harness-*${short}*.log; do
    if [[ -s "\$f" ]]; then exec tail -f "\$f"; fi
  done
  sleep 0.5
done
TAIL_SCRIPT
}

if [[ $n_graphs -eq 0 ]]; then
    # Standby mode — status pane only, will rebuild when runs appear
    tmux new-session -d -s "$SESSION" -n "standby" bash -c "$STATUS_SCRIPT"
fi

for ((page=0; page<n_pages; page++)); do
    page_label="page-$((page + 1))"
    start=$((page * PANES_PER_PAGE))

    page_graphs=()
    for ((i=start; i<start+PANES_PER_PAGE && i<n_graphs; i++)); do
        page_graphs+=("${SELECTED[$i]}")
    done
    n_on_page=${#page_graphs[@]}

    if [[ $page -eq 0 ]]; then
        tmux new-session -d -s "$SESSION" -n "$page_label" bash -c "$STATUS_SCRIPT"
    else
        tmux new-window -t "$SESSION" -n "$page_label" bash -c "$STATUS_SCRIPT"
    fi

    # Layout recipe:
    #   1. Split status (full width) from a bottom area (70% height)
    #   2. Split bottom into top-row and bottom-row (50/50)
    #   3. Split each row left/right (50/50)
    #
    # Result:
    #   pane 0: status (full width, top 30%)
    #   pane 1: tail-topleft    pane 2: tail-topright
    #   pane 3: tail-bottomleft pane 4: tail-bottomright

    # Step 1: status on top, tail-area below (70% to bottom)
    tmux split-window -t "$SESSION:$page_label.0" -v -l 70% \
        bash -c "$(tail_cmd "${page_graphs[0]}")"
    # Now: pane0=status, pane1=tail1

    if [[ $n_on_page -ge 2 ]]; then
        # Step 2: split pane1 into top-row / bottom-row (50/50 vertical)
        tmux split-window -t "$SESSION:$page_label.1" -v -l 50% \
            bash -c "$(tail_cmd "${page_graphs[1]}")"
        # Now: pane0=status, pane1=tail1(top), pane2=tail2(bottom)
    fi

    if [[ $n_on_page -ge 3 ]]; then
        # Step 3: split top-row (pane1) left/right
        tmux split-window -t "$SESSION:$page_label.1" -h -l 50% \
            bash -c "$(tail_cmd "${page_graphs[2]}")"
        # Now: pane0=status, pane1=tail1(TL), pane2=tail3(TR), pane3=tail2(bottom)
    fi

    if [[ $n_on_page -ge 4 ]]; then
        # Step 4: split bottom-row (pane3=tail2) left/right
        tmux split-window -t "$SESSION:$page_label.3" -h -l 50% \
            bash -c "$(tail_cmd "${page_graphs[3]}")"
        # Now: pane0=status, pane1=TL, pane2=TR, pane3=BL, pane4=BR
    fi
done

tmux select-window -t "${SESSION}:0"

# ---------------------------------------------------------------------------
# Keybindings — work from any pane, no Ctrl-b prefix needed
# ---------------------------------------------------------------------------
KILL_SCRIPT="${REPO_ROOT}/scripts/_bayes-kill.sh"
cat > "$KILL_SCRIPT" << 'KILLEOF'
#!/usr/bin/env bash
for lock in /tmp/bayes-harness-*.lock; do
    [[ -f "$lock" ]] || continue
    pid=$(cat "$lock" 2>/dev/null)
    if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then
        kill -- -"$pid" 2>/dev/null || kill "$pid" 2>/dev/null || true
    fi
    rm -f "$lock" 2>/dev/null
done
if [[ -f /tmp/bayes_recovery_pids ]]; then
    while read -r pid; do
        kill "$pid" 2>/dev/null || true
    done < /tmp/bayes_recovery_pids
    rm -f /tmp/bayes_recovery_pids
fi
KILLEOF
chmod +x "$KILL_SCRIPT"


# Keybindings: Ctrl-b + single lowercase letter (no modifiers)
# All letters verified free in default tmux bindings.
tmux bind-key -N "Kill all bayes"   k run-shell "${KILL_SCRIPT}"
tmux bind-key -N "Clear finished"   e run-shell "kill -USR1 \$(cat /tmp/_bayes_monitor_status_pid 2>/dev/null) 2>/dev/null || true"
tmux bind-key -N "Quit monitor"     g kill-session -t "${SESSION}"
tmux bind-key -N "Reload monitor"   j run-shell "${REPO_ROOT}/scripts/bayes-monitor.sh &"

# Also increase scrollback so tail panes are useful
tmux set-option -t "$SESSION" -g history-limit 10000

page_hint=""
if [[ $n_pages -gt 1 ]]; then
    page_hint="  Ctrl-b n/p: next/prev page (${n_pages} pages)"
fi

echo "Monitor: tmux attach -t ${SESSION}"
echo "  Top:    status (CPU + jobs)"
echo "  Bottom: up to 4 tail panes per page"
echo "  Keys:   k=kill all  r=reload  q=quit (no Ctrl-b needed)"
[[ -n "$page_hint" ]] && echo "$page_hint"
echo "  Ctrl-b ↑↓: switch pane  Ctrl-b [: scroll"
echo ""

if [[ -t 0 ]]; then
    exec tmux attach -t "$SESSION"
fi
