#!/usr/bin/env python3
"""Migrate old-format truth files to new format (with graph: section).

Reads each old-format truth file + its corresponding graph JSON,
extracts graph structure, and writes a new-format truth file.

The graph JSON provides: nodes (id, label, event_id, absorbing,
is_start) and edges (from, to via UUID lookup). The truth file
provides: edge parameters (p, onset, mu, sigma) and simulation config.

Usage:
    python bayes/migrate_truth_files.py                    # dry run
    python bayes/migrate_truth_files.py --write            # write files
    python bayes/migrate_truth_files.py --graph synth-X    # single graph
"""

import argparse
import json
import os
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
CONF_PATH = REPO_ROOT / ".private-repos.conf"


def _resolve_data_repo() -> Path:
    for line in CONF_PATH.read_text().splitlines():
        if line.startswith("DATA_REPO_DIR="):
            return REPO_ROOT / line.split("=", 1)[1].strip().strip('"')
    print("ERROR: DATA_REPO_DIR not found in .private-repos.conf")
    sys.exit(1)


def _is_old_format(truth: dict) -> bool:
    """Old format: has edges but no edge has 'from' field."""
    edges = truth.get("edges", {})
    if not edges:
        return False
    return not any(
        isinstance(v, dict) and "from" in v
        for v in edges.values()
    )


def _extract_graph_structure(graph_json: dict, graph_name: str, truth: dict) -> dict:
    """Extract new-format truth dict from old truth + graph JSON."""
    nodes_by_uuid = {n["uuid"]: n for n in graph_json.get("nodes", [])}

    # Identify start node
    start_node_id = None
    for n in graph_json["nodes"]:
        if n.get("entry", {}).get("is_start"):
            start_node_id = n["id"]
            break

    # Build nodes section
    nodes_section = {}
    for n in graph_json["nodes"]:
        nid = n["id"]
        # Skip dropout nodes (generated by graph_from_truth)
        if "dropout" in nid.lower():
            continue
        entry = {"label": n.get("label", nid)}
        if n.get("event_id"):
            entry["event_id"] = n["event_id"]
        if n.get("entry", {}).get("is_start"):
            entry["is_start"] = True
        if n.get("absorbing"):
            entry["absorbing"] = True
            entry["outcome_type"] = n.get("outcome_type", "success")
        nodes_section[nid] = entry

    # Build edges section: merge truth params with from/to from graph JSON
    edges_section = {}
    old_edges = truth.get("edges", {})

    for edge in graph_json.get("edges", []):
        pid = edge.get("p", {}).get("id", "")
        if not pid:
            continue  # skip complement/dropout edges

        from_node = nodes_by_uuid.get(edge["from"], {})
        to_node = nodes_by_uuid.get(edge["to"], {})
        from_id = from_node.get("id", "")
        to_id = to_node.get("id", "")

        if not from_id or not to_id:
            continue
        # Skip dropout edges
        if "dropout" in from_id.lower() or "dropout" in to_id.lower():
            continue

        # Get truth params for this edge
        truth_params = old_edges.get(pid, {})

        entry = {
            "from": from_id,
            "to": to_id,
        }
        # Copy all truth params (p, onset, mu, sigma, kappa_sim, etc.)
        for k, v in truth_params.items():
            entry[k] = v

        edges_section[pid] = entry

    # Build graph section. raw_ids: true tells graph_from_truth.py to
    # use node/edge IDs as-is (no prefixing), since these IDs predate
    # the prefixing convention.
    graph_section = {
        "name": graph_name,
        "raw_ids": True,
    }
    desc = graph_json.get("metadata", {}).get("description", "")
    if desc:
        graph_section["description"] = desc
    if start_node_id:
        graph_section["anchor"] = start_node_id

    # Assemble new truth
    new_truth = {}

    # Preserve any leading comments by reading the original file
    # (yaml.dump won't preserve them, so we reconstruct)
    new_truth["graph"] = graph_section
    new_truth["nodes"] = nodes_section
    new_truth["edges"] = edges_section

    # Copy simulation section
    if "simulation" in truth:
        new_truth["simulation"] = truth["simulation"]

    # Copy optional sections
    for key in ("context_dimensions", "emit_context_slices", "testing"):
        if key in truth:
            new_truth[key] = truth[key]

    return new_truth


def migrate_one(graph_name: str, data_repo: Path, *, write: bool = False) -> bool:
    """Migrate a single truth file. Returns True if migration was needed."""
    graphs_dir = data_repo / "graphs"
    truth_path = graphs_dir / f"{graph_name}.truth.yaml"
    json_path = graphs_dir / f"{graph_name}.json"

    if not truth_path.exists():
        print(f"  SKIP: {graph_name} — no truth file")
        return False

    with open(truth_path) as f:
        truth = yaml.safe_load(f)

    if not _is_old_format(truth):
        print(f"  SKIP: {graph_name} — already new format")
        return False

    if not json_path.exists():
        print(f"  ERROR: {graph_name} — no graph JSON at {json_path}")
        return False

    with open(json_path) as f:
        graph_json = json.load(f)

    new_truth = _extract_graph_structure(graph_json, graph_name, truth)

    # Read original file to preserve leading comments
    original_lines = truth_path.read_text().splitlines()
    comment_lines = []
    for line in original_lines:
        if line.startswith("#") or line.strip() == "":
            comment_lines.append(line)
        else:
            break

    # Validate: new format should have nodes with from/to edges
    edge_count = sum(1 for e in new_truth["edges"].values() if "from" in e)
    node_count = len(new_truth.get("nodes", {}))
    print(f"  {graph_name}: {node_count} nodes, {edge_count} edges (from {len(truth.get('edges', {}))} old edges)")

    if write:
        # Write new truth file
        output = ""
        if comment_lines:
            output = "\n".join(comment_lines) + "\n\n"
        output += yaml.dump(new_truth, default_flow_style=False, sort_keys=False, allow_unicode=True)
        truth_path.write_text(output)
        print(f"    WROTE: {truth_path}")

    return True


def main():
    parser = argparse.ArgumentParser(description="Migrate old-format truth files to new format")
    parser.add_argument("--write", action="store_true", help="Actually write files (default: dry run)")
    parser.add_argument("--graph", type=str, help="Migrate a single graph (default: all)")
    args = parser.parse_args()

    data_repo = _resolve_data_repo()
    graphs_dir = data_repo / "graphs"

    if args.graph:
        names = [args.graph]
    else:
        names = sorted(
            p.stem.replace(".truth", "")
            for p in graphs_dir.glob("*.truth.yaml")
        )

    migrated = 0
    for name in names:
        if migrate_one(name, data_repo, write=args.write):
            migrated += 1

    mode = "WROTE" if args.write else "DRY RUN"
    print(f"\n{mode}: {migrated}/{len(names)} files {'migrated' if args.write else 'would be migrated'}")


if __name__ == "__main__":
    main()
